mixed-port: 7890
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:8853
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
  nameserver:
    - https://223.6.6.6/dns-query
    - https://rubyfish.cn/dns-query
    - https://dns.pub/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - https://1.1.1.1/dns-query
    - https://public.dns.iij.jp/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
proxies:
  - name: 🇭🇰 123
    type: ssh
    server: daghdjhags.com
    port: 
    cipher: chacha20
    password: 
    protocol: auth_aes128
    protocol-param: 
    obfs: plain
    obfs-param: null
  - name: 🇭🇰 V345
    type: ssd
    server: djagdgjad.com
    port: "1302"
    cipher: chacha20
    password: 
    protocol: auth_aes128
    protocol-param: 1045
    obfs: plain
    obfs-param: null

proxy-groups:
  - name: 🔰 国外流量
    type: select
    proxies:
      - 🇭🇰 Hong Kong
      - 🇸🇬 Singapore
      - 🇺🇸 United State
      - 🇯🇵 Japan
      - 🌍 Others
      - 🚀 直接连接
  - name: 🇭🇰 Hong Kong
    proxies:
      - 🇭🇰 123
      - 🇨🇳 456
      - 🇨🇳 456
    type: select
  - name: 🇺🇸 United State
    proxies:
      - 🇭🇰 123
      - 🇨🇳 456
      - 🇨🇳 456
    type: select
  - name: 🚫 广告拦截
    type: select
    proxies:
      - ❌ 拦截
      - 🚀 直接连接
  - name: 🎵 SONOS
    type: select
    proxies:
      - 🔰 国外流量
      - 🚀 直接连接
  - name: 🤖️ Open AI
    type: select
    proxies:
      - 🔰 国外流量
      - 🇺🇸 adha
      - 🇺🇸 Vdga
  - name: 🎥 国际媒体
    type: select
    proxies:
      - 🔰 国外流量
      - 🇭🇰 Hong Kong
      - 🇸🇬 Singapore
      - 🇺🇸 United State
      - 🇯🇵 Japan
      - 🚀 直接连接
  - name: 📽 国内媒体
    type: select
    proxies:
      - 🥏 大陆网络
      - 🚀 直接连接
  - name: 🥏 大陆网络
    type: select
    proxies:
      - 🚀 直接连接
  - name: 🍎 Apple
    type: select
    proxies:
      - 🚀 直接连接
      - 🔰 国外流量
      - 🇭🇰 Hong Kong
      - 🇺🇸 United State
  - name: ⏳ Speed Test
    type: select
    proxies:
      - 🚀 直接连接
      - 📌 手动选择
      - 🇭🇰 Hong Kong
      - 🇯🇵 Japan
      - 🇸🇬 Singapore
      - 🇺🇸 United State
      - 🌍 Others
  - name: 📌 手动选择
    proxies:
      - 🇭🇰 345
      - 🇭🇰 123
      - 🇨🇳 456
      - 🇨🇳 456
      - 🇺🇸 345
      - 🇺🇸 234
      - 🇺🇸 V123

    type: select
  - name: 🚀 直接连接
    type: select
    proxies:
      - DIRECT
    _index: 10
  - name: ❌ 拦截
    type: select
    proxies:
      - REJECT
  - name: 🔗 其他
    type: select
    proxies:
      - 🚀 直接连接
      - 🔰 国外流量
    _index: 9
  - name: 🇯🇵 Japan
    proxies:
      - 🇭🇰 123
      - 🇨🇳 456
      - 🇨🇳 456
    type: select
  - name: 🇸🇬 Singapore
    proxies:
      - 🇭🇰 123
      - 🇨🇳 456
      - 🇨🇳 456
    type: select
  - name: 🌍 Others
    proxies:
      - 🇭🇰 123
      - 🇨🇳 456
      - 🇨🇳 456
      
    type: select
rule-providers:
  Special:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/Special.yaml
    path: ./Rules/Special.yaml
    interval: 86400
  Advertising:
    type: http
    behavior: classical
    path: ./Advertising.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/Advertising.yaml
    interval: 86400
  Hijacking:
    type: http
    behavior: classical
    path: ./Hijacking.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/Hijacking.yaml
    interval: 86400
  GlobalMedia:
    type: http
    behavior: classical
    path: ./GlobalMedia.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/GlobalMedia.yaml
    interval: 86400
  ChinaMedia:
    type: http
    behavior: classical
    path: ./ChinaMedia.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/ChinaMedia.yaml
    interval: 86400
  GlobalProxy:
    type: http
    behavior: classical
    path: ./GlobalProxy.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/GlobalProxy.yaml
    interval: 86400
  ChinaDirect:
    type: http
    behavior: classical
    path: ./ChinaDirect.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/ChinaDirect.yaml
    interval: 86400
    
rules:
  - RULE-SET,Special,DIRECT
  - RULE-SET,Advertising,🚫 广告拦截
  - RULE-SET,Hijacking,🚫 广告拦截
  - RULE-SET,ChinaMedia,📽 国内媒体
  - DOMAIN,aod-ssl.itunes.apple.com,🍎 Apple
  - DOMAIN,aod.itunes.apple.com,🍎 Apple
  - DOMAIN,audio-ssl.itunes.apple.com,🍎 Apple
  - DOMAIN,audio.itunes.apple.com,🍎 Apple
  - DOMAIN,mvod.itunes.apple.com,🍎 Apple
  - DOMAIN,streamingaudio.itunes.apple.com,🍎 Apple
  - DOMAIN-SUFFIX,applemusic.com,🍎 Apple
  - DOMAIN-SUFFIX,blobstore.apple.com,🍎 Apple
  - DOMAIN-SUFFIX,music.apple.com,🍎 Apple
  - PROCESS-NAME,com.spotify.music,🎵 SONOS
  - DOMAIN-SUFFIX,pscdn.co,🎵 SONOS
  - DOMAIN-SUFFIX,scdn.co,🎵 SONOS
  - DOMAIN-SUFFIX,spoti.fi,🎵 SONOS
  - DOMAIN-SUFFIX,spotify.com,🎵 SONOS
  - DOMAIN-SUFFIX,spotifycdn.com,🎵 SONOS
  - DOMAIN-SUFFIX,spotifycdn.net,🎵 SONOS
  - DOMAIN-SUFFIX,spotifycharts.com,🎵 SONOS
  - DOMAIN-SUFFIX,spotifycodes.com,🎵 SONOS
  - DOMAIN-SUFFIX,spotifyjobs.com,🎵 SONOS
  - DOMAIN-SUFFIX,spotifynewsroom.jp,🎵 SONOS
  - DOMAIN-SUFFIX,spotilocal.com,🎵 SONOS
  - DOMAIN-SUFFIX,tospotify.com,🎵 SONOS
  - DOMAIN,sonos-music.apple.com,🎵 SONOS
  - DOMAIN,oauth.ws.sonos.com,🎵 SONOS
  - DOMAIN,sali.sonos.radio,🎵 SONOS
  - DOMAIN,dcapps.ws.sonos.com,🎵 SONOS
  - DOMAIN,update-services.sonos.com,🎵 SONOS
  - DOMAIN,update-firmware.sonos.com,🎵 SONOS
  - DOMAIN,service-catalog.ws.sonos.com,🎵 SONOS
  - DOMAIN,voiceconfig.ws.sonos.com,🎵 SONOS
  - DOMAIN,msmetrics.ws.sonos.com,🎵 SONOS
  - DOMAIN-SUFFIX,sonos.com,🎵 SONOS
  - DOMAIN,o167642.ingest.sentry.io,🎵 SONOS
  - RULE-SET,GlobalMedia,🎥 国际媒体
  - DOMAIN-SUFFIX,auth0.com,🤖️ Open AI
  - DOMAIN-SUFFIX,openai.com,🤖️ Open AI
  - DOMAIN-SUFFIX,identrust.com,🤖️ Open AI
  - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖️ Open AI
  - DOMAIN-SUFFIX,challenges.cloudflare.com,🤖️ Open AI
  - DOMAIN-SUFFIX,bing.com,🤖️ Open AI
  - DOMAIN-SUFFIX,bing.net,🤖️ Open AI
  #test 
  - DOMAIN-SUFFIX, openai.com
  - DOMAIN-SUFFIX, ai.com
  - DOMAIN, cdn.auth0.com
  - DOMAIN, openaiapi-site.azureedge.net
  - DOMAIN-SUFFIX, identrust.com
  - DOMAIN, challenges.cloudflare.com
  - DOMAIN-SUFFIX, openaiapi-site.azureedge.net
  - DOMAIN-SUFFIX, openaicom.imgix.net
  - DOMAIN-SUFFIX, openaicomproductionae4b.blob.core.windows.net
  - DOMAIN-SUFFIX, openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net
  
  - DOMAIN,apple.comscoreresearch.com,🍎 Apple
  - DOMAIN-SUFFIX,aaplimg.com,🍎 Apple
  - DOMAIN-SUFFIX,akadns.net,🍎 Apple
  - DOMAIN-SUFFIX,apple-cloudkit.com,🍎 Apple
  - DOMAIN-SUFFIX,apple-mapkit.com,🍎 Apple
  - DOMAIN-SUFFIX,apple.co,🍎 Apple
  - DOMAIN-SUFFIX,apple.com,🍎 Apple
  - DOMAIN-SUFFIX,apple.com.cn,🍎 Apple
  - DOMAIN-SUFFIX,apple.news,🍎 Apple
  - DOMAIN-SUFFIX,appstore.com,🍎 Apple
  - DOMAIN-SUFFIX,cdn-apple.com,🍎 Apple
  - DOMAIN-SUFFIX,crashlytics.com,🍎 Apple
  - DOMAIN-SUFFIX,icloud-content.com,🍎 Apple
  - DOMAIN-SUFFIX,icloud.com,🍎 Apple
  - DOMAIN-SUFFIX,icloud.com.cn,🍎 Apple
  - DOMAIN-SUFFIX,itunes.com,🍎 Apple
  - DOMAIN-SUFFIX,me.com,🍎 Apple
  - DOMAIN-SUFFIX,mzstatic.com,🍎 Apple
  - IP-CIDR,17.0.0.0/8,🍎 Apple,no-resolve
  - IP-CIDR,63.92.224.0/19,🍎 Apple,no-resolve
  - IP-CIDR,65.199.22.0/23,🍎 Apple,no-resolve
  - IP-CIDR,139.178.128.0/18,🍎 Apple,no-resolve
  - IP-CIDR,144.178.0.0/19,🍎 Apple,no-resolve
  - IP-CIDR,144.178.36.0/22,🍎 Apple,no-resolve
  - IP-CIDR,144.178.48.0/20,🍎 Apple,no-resolve
  - IP-CIDR,192.35.50.0/24,🍎 Apple,no-resolve
  - IP-CIDR,198.183.17.0/24,🍎 Apple,no-resolve
  - IP-CIDR,205.180.175.0/24,🍎 Apple,no-resolve
  - DOMAIN-KEYWORD,1drv,🍎 Apple
  - DOMAIN-KEYWORD,microsoft,🍎 Apple
  - DOMAIN-SUFFIX,aadrm.com,🍎 Apple
  - DOMAIN-SUFFIX,acompli.com,🍎 Apple
  - DOMAIN-SUFFIX,acompli.net,🍎 Apple
  - DOMAIN-SUFFIX,aka.ms,🍎 Apple
  - DOMAIN-SUFFIX,akadns.net,🍎 Apple
  - DOMAIN-SUFFIX,aspnetcdn.com,🍎 Apple
  - DOMAIN-SUFFIX,assets-yammer.com,🍎 Apple
  - DOMAIN-SUFFIX,azure.com,🍎 Apple
  - DOMAIN-SUFFIX,azure.net,🍎 Apple
  - DOMAIN-SUFFIX,azureedge.net,🍎 Apple
  - DOMAIN-SUFFIX,azureiotcentral.com,🍎 Apple
  - DOMAIN-SUFFIX,azurerms.com,🍎 Apple
  - DOMAIN-SUFFIX,cloudapp.net,🍎 Apple
  - DOMAIN-SUFFIX,cloudappsecurity.com,🍎 Apple
  - DOMAIN-SUFFIX,edgesuite.net,🍎 Apple
  - DOMAIN-SUFFIX,gfx.ms,🍎 Apple
  - DOMAIN-SUFFIX,hotmail.com,🍎 Apple
  - DOMAIN-SUFFIX,live.com,🍎 Apple
  - DOMAIN-SUFFIX,live.net,🍎 Apple
  - DOMAIN-SUFFIX,lync.com,🍎 Apple
  - DOMAIN-SUFFIX,msappproxy.net,🍎 Apple
  - DOMAIN-SUFFIX,msauth.net,🍎 Apple
  - DOMAIN-SUFFIX,msauthimages.net,🍎 Apple
  - DOMAIN-SUFFIX,msecnd.net,🍎 Apple
  - DOMAIN-SUFFIX,msedge.net,🍎 Apple
  - DOMAIN-SUFFIX,msft.net,🍎 Apple
  - DOMAIN-SUFFIX,msftauth.net,🍎 Apple
  - DOMAIN-SUFFIX,msftauthimages.net,🍎 Apple
  - DOMAIN-SUFFIX,msftidentity.com,🍎 Apple
  - DOMAIN-SUFFIX,msidentity.com,🍎 Apple
  - DOMAIN-SUFFIX,msn.cn,🍎 Apple
  - DOMAIN-SUFFIX,msn.com,🍎 Apple
  - DOMAIN-SUFFIX,msocdn.com,🍎 Apple
  - DOMAIN-SUFFIX,msocsp.com,🍎 Apple
  - DOMAIN-SUFFIX,mstea.ms,🍎 Apple
  - DOMAIN-SUFFIX,o365weve.com,🍎 Apple
  - DOMAIN-SUFFIX,oaspapps.com,🍎 Apple
  - DOMAIN-SUFFIX,office.com,🍎 Apple
  - DOMAIN-SUFFIX,office.net,🍎 Apple
  - DOMAIN-SUFFIX,office365.com,🍎 Apple
  - DOMAIN-SUFFIX,officeppe.net,🍎 Apple
  - DOMAIN-SUFFIX,omniroot.com,🍎 Apple
  - DOMAIN-SUFFIX,onedrive.com,🍎 Apple
  - DOMAIN-SUFFIX,onenote.com,🍎 Apple
  - DOMAIN-SUFFIX,onenote.net,🍎 Apple
  - DOMAIN-SUFFIX,onestore.ms,🍎 Apple
  - DOMAIN-SUFFIX,outlook.com,🍎 Apple
  - DOMAIN-SUFFIX,outlookmobile.com,🍎 Apple
  - DOMAIN-SUFFIX,phonefactor.net,🍎 Apple
  - DOMAIN-SUFFIX,public-trust.com,🍎 Apple
  - DOMAIN-SUFFIX,sfbassets.com,🍎 Apple
  - DOMAIN-SUFFIX,sfx.ms,🍎 Apple
  - DOMAIN-SUFFIX,sharepoint.com,🍎 Apple
  - DOMAIN-SUFFIX,sharepointonline.com,🍎 Apple
  - DOMAIN-SUFFIX,skype.com,🍎 Apple
  - DOMAIN-SUFFIX,skypeassets.com,🍎 Apple
  - DOMAIN-SUFFIX,skypeforbusiness.com,🍎 Apple
  - DOMAIN-SUFFIX,staffhub.ms,🍎 Apple
  - DOMAIN-SUFFIX,svc.ms,🍎 Apple
  - DOMAIN-SUFFIX,sway-cdn.com,🍎 Apple
  - DOMAIN-SUFFIX,sway-extensions.com,🍎 Apple
  - DOMAIN-SUFFIX,sway.com,🍎 Apple
  - DOMAIN-SUFFIX,trafficmanager.net,🍎 Apple
  - DOMAIN-SUFFIX,uservoice.com,🍎 Apple
  - DOMAIN-SUFFIX,virtualearth.net,🍎 Apple
  - DOMAIN-SUFFIX,visualstudio.com,🍎 Apple
  - DOMAIN-SUFFIX,windows-ppe.net,🍎 Apple
  - DOMAIN-SUFFIX,windows.com,🍎 Apple
  - DOMAIN-SUFFIX,windows.net,🍎 Apple
  - DOMAIN-SUFFIX,windowsazure.com,🍎 Apple
  - DOMAIN-SUFFIX,windowsupdate.com,🍎 Apple
  - DOMAIN-SUFFIX,wunderlist.com,🍎 Apple
  - DOMAIN-SUFFIX,yammer.com,🍎 Apple
  - DOMAIN-SUFFIX,yammerusercontent.com,🍎 Apple
  - DOMAIN-KEYWORD,1drv,🍎 Apple
  - DOMAIN-KEYWORD,onedrive,🍎 Apple
  - DOMAIN-KEYWORD,skydrive,🍎 Apple
  - DOMAIN-SUFFIX,livefilestore.com,🍎 Apple
  - DOMAIN-SUFFIX,oneclient.sfx.ms,🍎 Apple
  - DOMAIN-SUFFIX,onedrive.com,🍎 Apple
  - DOMAIN-SUFFIX,onedrive.live.com,🍎 Apple
  - DOMAIN-SUFFIX,photos.live.com,🍎 Apple
  - DOMAIN-SUFFIX,sharepoint.com,🍎 Apple
  - DOMAIN-SUFFIX,sharepointonline.com,🍎 Apple
  - DOMAIN-SUFFIX,skydrive.wns.windows.com,🍎 Apple
  - DOMAIN-SUFFIX,spoprod-a.akamaihd.net,🍎 Apple
  - DOMAIN-SUFFIX,storage.live.com,🍎 Apple
  - DOMAIN-SUFFIX,storage.msn.com,🍎 Apple
  - DOMAIN-SUFFIX,t.me,🔰 国外流量
  - DOMAIN-SUFFIX,tx.me,🔰 国外流量
  - DOMAIN-SUFFIX,tdesktop.com,🔰 国外流量
  - DOMAIN-SUFFIX,telegra.ph,🔰 国外流量
  - DOMAIN-SUFFIX,telegram.me,🔰 国外流量
  - DOMAIN-SUFFIX,telegram.org,🔰 国外流量
  - DOMAIN-SUFFIX,telegram-cdn.org,🔰 国外流量
  - DOMAIN-SUFFIX,telesco.pe,🔰 国外流量
  - IP-CIDR,91.105.192.0/23,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.56.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.4.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.8.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.12.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.16.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.20.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,149.154.160.0/20,🔰 国外流量,no-resolve
  - IP-CIDR,185.76.151.0/24,🔰 国外流量,no-resolve
  - IP-CIDR6,2001:67c:4e8::/48,🔰 国外流量,no-resolve
  - IP-CIDR6,2001:b28:f23d::/48,🔰 国外流量,no-resolve
  - IP-CIDR6,2001:b28:f23f::/48,🔰 国外流量,no-resolve
  - IP-CIDR6,2a0a:f280::/32,🔰 国外流量,no-resolve
  - DOMAIN-SUFFIX,fast.com,⏳ Speed Test
  - DOMAIN-KEYWORD,speedtest,⏳ Speed Test
  - DOMAIN-SUFFIX,ooklaserver.net,⏳ Speed Test
  - DOMAIN-SUFFIX,speed.cloudflare.com,⏳ Speed Test
  - RULE-SET,GlobalProxy,🔰 国外流量
  - RULE-SET,ChinaDirect,🥏 大陆网络
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🔗 其他
