#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者运行目录下的config.yml
#---------------------------------------------------#

## Update Jun 5. 2023  20:18  wiki github.com/Dreamacro/clash/wiki/configuration
## Update Aug 13. 2034  16:09  Firefox Apple push and For FakeIP mode use 

# 混合端口 HTTP和SOCKS5用一个端口 
mixed-port: 7890

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 
redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: true
# 规则模式：rule/ global/ direct/ script 
mode: Rule
# 设置日志输出级别
log-level: info

# Clash 的 RESTful API
external-controller: 0.0.0.0:9090
# 实验性功能
experimental:
  ignore-resolve-fail: true
  
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:8853
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'msftconnecttest.com'
    - 'msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.mcdn.bilivideo.cn'
  nameserver:
    - 223.5.5.5
    - 180.184.2.2
    - 114.114.114.114
proxy-groups:
  - name: 🔰 国外流量
    type: select
    proxies:
      - 🇭🇰 Hong Kong
      - 🇸🇬 Singapore
      - 🇺🇸 United State
      - 🇯🇵 Japan
      - 🌍 Taiwan
      - 🚀 直接连接
  - name: 🇭🇰 Hong Kong
    type: select
    use:
      - Subscription
    filter: "HongKong|HK|香港"
  - name: 🇺🇸 United State
    type: select
    use:
      - Subscription
    filter: "United State|US|美国"
  - name: 🇸🇬 Singapore
    use:
      - Subscription
    filter: "United State|US|新加坡"
    type: select
  - name: 🚫 广告拦截
    type: select
    proxies:
      - ❌ 拦截
      - 🚀 直接连接
  - name: 🎵 SONOS
    type: select
    proxies:
      - 🔰 国外流量
      - 🚀 直接连接
  - name: 🤖️ Open AI
    type: select
    proxies:
      - 🇺🇸 United State
      - 🇯🇵 Japan
      - 🇸🇬 Singapore
  - name: 🎥 国际媒体
    type: select
    proxies:
      - 🔰 国外流量
      - 🇭🇰 Hong Kong
      - 🇸🇬 Singapore
      - 🇺🇸 United State
      - 🇯🇵 Japan
      - 🚀 直接连接
  - name: 📽 国内媒体
    type: select
    proxies:
      - 🚀 直接连接
  - name: 🍎 Apple
    type: select
    proxies:
      - 🚀 直接连接
      - 🔰 国外流量
      - 🇭🇰 Hong Kong
      - 🇺🇸 United State
  - name: 🖥 Microsoft
    type: select
    proxies:
      - 🔰 国外流量 
      - 🇭🇰 Hong Kong
      - 🚀 直接连接
  - name: ⏳ Speed Test
    type: select
    proxies:
      - 🚀 直接连接
      - 📌 手动选择
      - 🇭🇰 Hong Kong
      - 🇯🇵 Japan
      - 🇸🇬 Singapore
      - 🇺🇸 United State
      - 🌍 Taiwan
  - name: 📌 手动选择
    proxies:
      - DIRECT
      - 🇭🇰 Hong Kong
      - 🇯🇵 Japan
      - 🇸🇬 Singapore
      - 🇺🇸 United State
      - 🌍 Taiwan
    type: select
  - name: 🚀 直接连接
    type: select
    proxies:
      - DIRECT
    _index: 10
  - name: ❌ 拦截
    type: select
    proxies:
      - REJECT
  - name: 🔗 其他
    type: select
    proxies:
      - 🚀 直接连接
      - 🔰 国外流量
    _index: 9
  - name: 🇯🇵 Japan
    type: select
    use:
      - Subscription
    filter: "Japan|JP|日本"
  - name: 🌍 Taiwan
    type: select
    use:
      - Subscription
    filter: "Taiwan|TW|台湾"
proxy-providers:
  Subscription:
    type: http
    url: "URL"
    path: ./providers/Subscription.yaml
    interval: 86400
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
rule-providers:
  Special:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/Special.yaml
    path: ./Rules/Special.yaml
    interval: 86400
  Advertising:
    type: http
    behavior: classical
    path: ./Advertising.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/Advertising.yaml
    interval: 86400
  Hijacking:
    type: http
    behavior: classical
    path: ./Hijacking.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/Hijacking.yaml
    interval: 86400
  GlobalMedia:
    type: http
    behavior: classical
    path: ./GlobalMedia.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/GlobalMedia.yaml
    interval: 86400
  ChinaMedia:
    type: http
    behavior: classical
    path: ./ChinaMedia.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/ChinaMedia.yaml
    interval: 86400
  GlobalProxy:
    type: http
    behavior: classical
    path: ./GlobalProxy.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/GlobalProxy.yaml
    interval: 86400
  ChinaDirect:
    type: http
    behavior: classical
    path: ./ChinaDirect.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/ChinaDirect.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    path: ./Microsoft.yaml
    url: https://raw.githubusercontent.com/gemnioo/MixedCFWRules/main/Clash/Microsoft.yaml
    interval: 86400
rules:
  - DOMAIN,translate.googleapis.com,🔰 国外流量
  - DOMAIN,api-edge.cognitive.microsofttranslator.com,📌 手动选择
  - DOMAIN,immersive-translate.owenyoung.com,📌 手动选择
  - DOMAIN,config.immersivetranslate.com,📌 手动选择
  - DOMAIN-SUFFIX,immersivetranslate.com,📌 手动选择
  - DOMAIN,immersivetranslate.substack.com,🔰 国外流量
  - RULE-SET,Special,DIRECT 
  - RULE-SET,Advertising,🚫 广告拦截
  - RULE-SET,Hijacking,🚫 广告拦截
  - DOMAIN,ddrk.me,🔰 国外流量
  - RULE-SET,ChinaMedia,📽 国内媒体
  - DOMAIN,aod-ssl.itunes.apple.com,🍎 Apple
  - DOMAIN,aod.itunes.apple.com,🍎 Apple
  - DOMAIN,audio-ssl.itunes.apple.com,🍎 Apple
  - DOMAIN,audio.itunes.apple.com,🍎 Apple
  - DOMAIN,mvod.itunes.apple.com,🍎 Apple
  - DOMAIN,inappcheck.itunes.apple.com,🍎 Apple
  - DOMAIN,streamingaudio.itunes.apple.com,🍎 Apple
  - DOMAIN-SUFFIX,applemusic.com,🍎 Apple
  - DOMAIN-SUFFIX,blobstore.apple.com,🍎 Apple
  - DOMAIN-SUFFIX,music.apple.com,🍎 Apple
  - DOMAIN,linear.tv.apple.com,🔰 国外流量
  - DOMAIN,uts-api.itunes.apple.com,🔰 国外流量
  - DOMAIN,np-edge.itunes.apple.com,🔰 国外流量
  - DOMAIN,play-edge.itunes.apple.com,🔰 国外流量
  - DOMAIN-SUFFIX,tv.apple.com,🔰 国外流量
  - PROCESS-NAME,com.spotify.music,🎵 SONOS
  - DOMAIN-SUFFIX,pscdn.co,🎵 SONOS
  - DOMAIN-SUFFIX,scdn.co,🎵 SONOS
  - DOMAIN-SUFFIX,spoti.fi,🎵 SONOS
  - DOMAIN-SUFFIX,spotify.com,🎵 SONOS
  - DOMAIN-SUFFIX,spotifycdn.com,🎵 SONOS
  - DOMAIN-SUFFIX,spotifycdn.net,🎵 SONOS
  - DOMAIN-SUFFIX,spotifycharts.com,🎵 SONOS
  - DOMAIN-SUFFIX,spotifycodes.com,🎵 SONOS
  - DOMAIN-SUFFIX,spotifyjobs.com,🎵 SONOS
  - DOMAIN-SUFFIX,spotifynewsroom.jp,🎵 SONOS
  - DOMAIN-SUFFIX,spotilocal.com,🎵 SONOS
  - DOMAIN-SUFFIX,tospotify.com,🎵 SONOS
  - DOMAIN,sonos-music.apple.com,🎵 SONOS
  - DOMAIN,oauth.ws.sonos.com,🎵 SONOS
  - DOMAIN,sali.sonos.radio,🎵 SONOS
  - DOMAIN,dcapps.ws.sonos.com,🎵 SONOS
  - DOMAIN,update-services.sonos.com,🎵 SONOS
  - DOMAIN,update-firmware.sonos.com,🎵 SONOS
  - DOMAIN,service-catalog.ws.sonos.com,🎵 SONOS
  - DOMAIN,voiceconfig.ws.sonos.com,🎵 SONOS
  - DOMAIN,msmetrics.ws.sonos.com,🎵 SONOS
  - DOMAIN-SUFFIX,sonos.com,🎵 SONOS
  - DOMAIN,o167642.ingest.sentry.io,REJECT
  - RULE-SET,GlobalMedia,🎥 国际媒体
  - DOMAIN-SUFFIX,jable.tv,🎥 国际媒体
  - DOMAIN-SUFFIX,mushroomtrack.com,🎥 国际媒体
  - DOMAIN,bard.google.com,🤖️ Open AI
  - DOMAIN,cdn.usefathom.com,🤖️ Open AI
  - DOMAIN-SUFFIX,anthropic.com,🤖️ Open AI
  - DOMAIN-SUFFIX,claude.ai,🤖️ Open AI
  - DOMAIN-SUFFIX,openai.com,🤖️ Open AI
  - DOMAIN-SUFFIX,identrust.com,🤖️ Open AI
  - DOMAIN,cdn.auth0.com,🤖️ Open AI
  - DOMAIN,ios.chat.openai.com,🤖️ Open AI
  - DOMAIN,challenges.cloudflare.com,🤖️ Open AI
  - DOMAIN,chat.openai.com.cdn.cloudflare.net,🤖️ Open AI
  - DOMAIN,openaiapi-site.azureedge.net,🤖️ Open AI
  - DOMAIN,openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net,🤖️ Open AI
  - DOMAIN,openaicomproductionae4b.blob.core.windows.net,🤖️ Open AI
  - DOMAIN,production-openaicom-storage.azureedge.net,🤖️ Open AI
  - DOMAIN,openaicom.imgix.net,REJECT
  - DOMAIN,o33249.ingest.sentry.io,REJECT
  - DOMAIN,o315582.ingest.sentry.io,REJECT
  - DOMAIN,o245571.ingest.sentry.io,REJECT
  - DOMAIN-SUFFIX,mc.tritondigital.com,🔰 国外流量
  - DOMAIN-KEYWORD,courier.push.apple.com,🔰 国外流量
  - DOMAIN,chtbl.com,🍎 Apple
  - DOMAIN,podtrac.com,🍎 Apple
  - DOMAIN-KEYWORD,apac-china-courier,🍎 Apple
  - DOMAIN,apple.comscoreresearch.com,🍎 Apple
  - DOMAIN-SUFFIX,aaplimg.com,🍎 Apple
  - DOMAIN-SUFFIX,akadns.net,🍎 Apple
  - DOMAIN-SUFFIX,akamaiedge.net,🍎 Apple
  - DOMAIN-SUFFIX,apple-cloudkit.com,🍎 Apple
  - DOMAIN-SUFFIX,apple-mapkit.com,🍎 Apple
  - DOMAIN-SUFFIX,apple.co,🍎 Apple
  - DOMAIN-SUFFIX,apple.com,🍎 Apple
  - DOMAIN-SUFFIX,apple.com.cn,🍎 Apple
  - DOMAIN-SUFFIX,apple.news,🍎 Apple
  - DOMAIN-SUFFIX,appstore.com,🍎 Apple
  - DOMAIN-SUFFIX,cdn-apple.com,🍎 Apple
  - DOMAIN-SUFFIX,crashlytics.com,🍎 Apple
  - DOMAIN-SUFFIX,icloud-content.com,🍎 Apple
  - DOMAIN-SUFFIX,icloud.com,🍎 Apple
  - DOMAIN-SUFFIX,icloud.com.cn,🍎 Apple
  - DOMAIN-SUFFIX,itunes.com,🍎 Apple
  - DOMAIN-SUFFIX,me.com,🍎 Apple
  - DOMAIN-SUFFIX,mzstatic.com,🍎 Apple
  - IP-CIDR,17.0.0.0/8,🍎 Apple,no-resolve
  - IP-CIDR,63.92.224.0/19,🍎 Apple,no-resolve
  - IP-CIDR,65.199.22.0/23,🍎 Apple,no-resolve
  - IP-CIDR,139.178.128.0/18,🍎 Apple,no-resolve
  - IP-CIDR,144.178.0.0/19,🍎 Apple,no-resolve
  - IP-CIDR,144.178.36.0/22,🍎 Apple,no-resolve
  - IP-CIDR,144.178.48.0/20,🍎 Apple,no-resolve
  - IP-CIDR,192.35.50.0/24,🍎 Apple,no-resolve
  - IP-CIDR,198.183.17.0/24,🍎 Apple,no-resolve
  - IP-CIDR,205.180.175.0/24,🍎 Apple,no-resolve
  - DOMAIN-SUFFIX,21vbc.com,DIRECT
  - DOMAIN-SUFFIX,21vbluecloud.com,DIRECT
  - DOMAIN-SUFFIX,21vbluecloud.net,DIRECT
  - DOMAIN-SUFFIX,azure.cn.cn,DIRECT
  - DOMAIN-SUFFIX,azure-dns-2.cn,DIRECT
  - DOMAIN-SUFFIX,azure-dns-4.cn,DIRECT
  - DOMAIN-SUFFIX,aadrm.cn,DIRECT
  - DOMAIN-SUFFIX,aggresmart.com,DIRECT
  - DOMAIN-SUFFIX,apihub-internal.cn,DIRECT
  - DOMAIN-SUFFIX,appserviceenvironment.cn,DIRECT
  - DOMAIN-SUFFIX,azcrmc-test.cn,DIRECT
  - DOMAIN-SUFFIX,azcrmc.cn,DIRECT
  - DOMAIN-SUFFIX,azk8s.cn,DIRECT
  - DOMAIN-SUFFIX,aznbcontent.cn,DIRECT
  - DOMAIN-SUFFIX,aztask.cn,DIRECT
  - DOMAIN-SUFFIX,azure-api.cn,DIRECT
  - DOMAIN-SUFFIX,azure-apihub.cn,DIRECT
  - DOMAIN-SUFFIX,azure-automation.cn,DIRECT
  - DOMAIN-SUFFIX,azure-connectedvehicles-stage.cn,DIRECT
  - DOMAIN-SUFFIX,azure-connectedvehicles.cn,DIRECT
  - DOMAIN-SUFFIX,azure-devices-provisioning.cn,DIRECT
  - DOMAIN-SUFFIX,azure-devices.cn,DIRECT
  - DOMAIN-SUFFIX,azure-dns.cn,DIRECT
  - DOMAIN-SUFFIX,azure-mobile.cn.cn,DIRECT
  - DOMAIN-SUFFIX,azure.cn,DIRECT
  - DOMAIN-SUFFIX,azurecr-test.cn,DIRECT
  - DOMAIN-SUFFIX,azurecr.cn,DIRECT
  - DOMAIN-SUFFIX,azurehdinsight.cn,DIRECT
  - DOMAIN-SUFFIX,azureiotsuite.cn,DIRECT
  - DOMAIN-SUFFIX,azuremresolver.cn,DIRECT
  - DOMAIN-SUFFIX,azureprivatedns.cn,DIRECT
  - DOMAIN-SUFFIX,azurerms.cn,DIRECT
  - DOMAIN-SUFFIX,azuresandbox.cn,DIRECT
  - DOMAIN-SUFFIX,b2clogin.cn,DIRECT
  - DOMAIN-SUFFIX,b3itech.cn,DIRECT
  - DOMAIN-SUFFIX,bing.com.cn,DIRECT
  - DOMAIN-SUFFIX,cegid-cloud.cn,DIRECT
  - DOMAIN-SUFFIX,chinacloud-mobile.cn,DIRECT
  - DOMAIN-SUFFIX,chinacloudapi.cn,DIRECT
  - DOMAIN-SUFFIX,chinacloudapp.cn,DIRECT
  - DOMAIN-SUFFIX,chinacloudsites.cn,DIRECT
  - DOMAIN-SUFFIX,cn.bing.com,DIRECT
  - DOMAIN-SUFFIX,cn.bing.net,DIRECT
  - DOMAIN-SUFFIX,dynamics.cn,DIRECT
  - DOMAIN-SUFFIX,hdinsightservices.cn,DIRECT
  - DOMAIN-SUFFIX,lync.cn,DIRECT
  - DOMAIN-SUFFIX,mcchcdn.com,DIRECT
  - DOMAIN-SUFFIX,mgmt-azure-api.cn,DIRECT
  - DOMAIN-SUFFIX,microsoft-smb.cn,DIRECT
  - DOMAIN-SUFFIX,mncmsidlab1.cn,DIRECT
  - DOMAIN-SUFFIX,msappproxy.cn,DIRECT
  - DOMAIN-SUFFIX,msauth.cn,DIRECT
  - DOMAIN-SUFFIX,msauthimages.cn,DIRECT
  - DOMAIN-SUFFIX,msftauth.cn,DIRECT
  - DOMAIN-SUFFIX,msftauthimages.cn,DIRECT
  - DOMAIN-SUFFIX,msftcloudes.cn,DIRECT
  - DOMAIN-SUFFIX,msidentity.cn,DIRECT
  - DOMAIN-SUFFIX,msidlabpbmc.cn,DIRECT
  - DOMAIN-SUFFIX,o365cn.com,DIRECT
  - DOMAIN-SUFFIX,o365files.cn,DIRECT
  - DOMAIN-SUFFIX,office365-net.cn,DIRECT
  - DOMAIN-SUFFIX,office365.cn,DIRECT
  - DOMAIN-SUFFIX,officewebapps.cn,DIRECT
  - DOMAIN-SUFFIX,onmschina.cn,DIRECT
  - DOMAIN-SUFFIX,outlook.cn,DIRECT
  - DOMAIN-SUFFIX,pbiwebcontent.cn,DIRECT
  - DOMAIN-SUFFIX,powerapps.cn,DIRECT
  - DOMAIN-SUFFIX,powerappsportals.cn,DIRECT
  - DOMAIN-SUFFIX,powerautomate.cn,DIRECT
  - DOMAIN-SUFFIX,powerbi.cn,DIRECT
  - DOMAIN-SUFFIX,reactorms.com.cn,DIRECT
  - DOMAIN-SUFFIX,sharepoint.cn,DIRECT
  - DOMAIN-SUFFIX,trafficmanager.cn,DIRECT
  - DOMAIN-SUFFIX,trustcenter.cn,DIRECT
  - DOMAIN-SUFFIX,unity3dcloud.cn,DIRECT
  - DOMAIN-SUFFIX,windowsazure.cn,DIRECT
  - DOMAIN-SUFFIX,windowsazurestatus.cn,DIRECT
  - DOMAIN-SUFFIX,microsoftonline.cn,DIRECT
  - DOMAIN-SUFFIX,microsoftonline-m.cn,DIRECT
  - DOMAIN-SUFFIX,microsoftonline-m-i.cn,DIRECT
  - DOMAIN-SUFFIX,microsoftazurestatus.cn,DIRECT
  - DOMAIN-SUFFIX,management-azure-devices-provisioning.cn,DIRECT
  - DOMAIN-SUFFIX,management-azure-devices.cn,DIRECT
  - RULE-SET,Microsoft,🖥 Microsoft
  - DOMAIN-SUFFIX,t.me,🔰 国外流量
  - DOMAIN-SUFFIX,tx.me,🔰 国外流量
  - DOMAIN-SUFFIX,tdesktop.com,🔰 国外流量
  - DOMAIN-SUFFIX,telegra.ph,🔰 国外流量
  - DOMAIN-SUFFIX,telegram.me,🔰 国外流量
  - DOMAIN-SUFFIX,telegram.org,🔰 国外流量
  - DOMAIN-SUFFIX,telegram-cdn.org,🔰 国外流量
  - DOMAIN-SUFFIX,telesco.pe,🔰 国外流量
  - IP-CIDR,91.105.192.0/23,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.56.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.4.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.8.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.12.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.16.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,91.108.20.0/22,🔰 国外流量,no-resolve
  - IP-CIDR,149.154.160.0/20,🔰 国外流量,no-resolve
  - IP-CIDR,149.154.165.0/20,🔰 国外流量,no-resolve
  - IP-CIDR,185.76.151.0/24,🔰 国外流量,no-resolve
  - IP-CIDR6,2001:67c:4e8::/48,🔰 国外流量,no-resolve
  - IP-CIDR6,2001:b28:f23d::/48,🔰 国外流量,no-resolve
  - IP-CIDR6,2001:b28:f23f::/48,🔰 国外流量,no-resolve
  - IP-CIDR6,2a0a:f280::/32,🔰 国外流量,no-resolve
  - DOMAIN-SUFFIX,fast.com,⏳ Speed Test
  - DOMAIN-KEYWORD,speedtest,⏳ Speed Test
  - DOMAIN-SUFFIX,ooklaserver.net,⏳ Speed Test
  - DOMAIN,cdn.cookielaw.org,⏳ Speed Test
  - DOMAIN,geolocation.onetrust.com,⏳ Speed Test
  - DOMAIN-SUFFIX,speed.cloudflare.com,⏳ Speed Test
  - DOMAIN,fastly.jsdelivr.net,⏳ Speed Test
  - RULE-SET,GlobalProxy,🔰 国外流量
  - RULE-SET,ChinaDirect,🚀 直接连接
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,17.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,🔗 其他
