## A Fly.io config file for OpenCat™ for Team that can be deployed directly
# fly.toml file generated for still-snowflake-6351 on 2023-03-30T09:53:40+08:00

app = "<input your own app name>"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
processes = []

[build]
  image = "bayedev/opencatd"

[mount]
  source = "opencat"
  destination = "/opt/db"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
